import numpy as np
from collections import Counter

def mean_squared_error(y_true, y_pred):
    """
    Calculates the Mean Squared Error (MSE).
    Formula: (1/n) * \sum (y_true - y_pred)^2
    """
    return np.mean((y_true - y_pred) ** 2)

def mean_absolute_error(y_true, y_pred):
    """
    Calculates the Mean Absolute Error (MAE).
    Formula: (1/n) * \sum |y_true - y_pred|
    """
    return np.mean(np.abs(y_true - y_pred))

def r2_score(y_true, y_pred):
    """
    Calculates the R^2 (Coefficient of Determination).
    Formula: 1 - (SS_res / SS_tot)
    where SS_res is the residual sum of squares and
    SS_tot is the total sum of squares.
    """
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    if ss_tot == 0:
        return 0.0

    return 1 - (ss_res / ss_tot)

def accuracy_score(y_true, y_pred):
    """
    Calculates the Accuracy classification score for binary classification.
    Formula: TP / (TP + TN + FP + FN)
    where TP is True Positives, TN is True Negatives, FP is False Positives, and FN is False Negatives.
    """
    tp = np.sum((y_true == 1) & (y_pred == 1))
    tn = np.sum((y_true == 0) & (y_pred == 0))
    fp = np.sum((y_true == 0) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))

    if tp + tn + fp + fn == 0:
        return 0.0

    return (tp + tn) / (tp + tn + fp + fn)

def precision_score(y_true, y_pred):
    """
    Calculates the Precision score for binary classification.
    Formula: TP / (TP + FP)
    where TP is True Positives and FP is False Positives.
    """
    tp = np.sum((y_true == 1) & (y_pred == 1))
    fp = np.sum((y_true == 0) & (y_pred == 1))

    if tp + fp == 0:
        return 0.0

    return tp / (tp + fp)

def recall_score(y_true, y_pred):
    """
    Calculates the Recall score for binary classification.
    Formula: TP / (TP + FN)
    where TP is True Positives and FN is False Negatives.
    """
    tp = np.sum((y_true == 1) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))

    if tp + fn == 0:
        return 0.0

    return tp / (tp + fn)

def f1_score(y_true, y_pred):
    """
    Calculates the F1 score for binary classification.
    Formula: 2 * (Precision * Recall) / (Precision + Recall)
    """
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)

    if precision + recall == 0:
        return 0.0

    return 2 * (precision * recall) / (precision + recall)

def purity_score(y_true, y_pred):
    """
    Calculates the Purity score for clustering.
    Formula: \frac{1}{n} \sum_{r=1}^{k} \max_i (n_r^i)
    """
    total_matches = 0

    # Iterate through each cluster generated by the model
    for cluster_id in np.unique(y_pred):
        # Find indices of data points belonging to this cluster
        cluster_indices = np.where(y_pred == cluster_id)[0]

        # Get the true labels of those data points
        true_labels_in_cluster = y_true[cluster_indices]

        # Find the count of the most dominant true label in this cluster
        if len(true_labels_in_cluster) > 0:
            most_common_count = Counter(true_labels_in_cluster).most_common(1)[0][1]
            total_matches += most_common_count

    # Divide by the total number of data points
    return total_matches / len(y_true)